Add python version check for csv writing
Also remove delimiter encoding as shouldn't be needed with unicode_literals and was causing me errors
Also move future to top of file to prevent error

SyntaxError: from __future__ imports must occur at the beginning of the file
TypeError: "delimiter" must be string, not bytes